config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :locations,          only: [:create, :destroy]

end

app/models/location.rb
class Location < ActiveRecord::Base
  # acts_as_gmappable
       def gmaps4rails_address
           address
       end
        def gmaps4rails_infowindow
          "<h4>#{name}</h4>" << "<h4>#{address}</h4>"
      end
  belongs_to :user
  validates :user_id, presence: true

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @location = current_user.locations.build(location_params)
    respond_to do |format|
      if @location.save
        format.html { redirect_to(current_user, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }

      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
        render 'static_pages/home'
      end
    end
  end

  def destroy
    @location = current_user.locations.find_by(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(request.referrer || root_url) }
      format.xml  { head :ok }
    end

  end

  private
    def location_params
      params.require(:location).permit(:name, :address)
    end

    def correct_user
      @location = current_user.locations.find_by(id: params[:id])
      redirect_to root_url if @location.nil?
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_location.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
        <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.address %></td>
    <td><%= location.longitude %></td>
    <td><%= location.latitude %></td>
    <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Location', root_url %>

</li>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>